#!/bin/bash
# =============================================================================
# Extract Assigned Read Counts from featureCounts Summary Files
# =============================================================================
# This script extracts the "Assigned" read count (2nd row, 2nd column) from
# each .summary file generated by featureCounts for mRNA, lncRNA, snRNA, snoRNA.
# Outputs tab-separated files with sample ID and assigned read counts.
# =============================================================================

# ----------------------------- Configuration ---------------------------------
# Project root directory (change if needed)
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

# Input directory containing featureCounts .summary files
INPUT_DIR="${PROJECT_ROOT}/results/featureCounts"

# Output directory for summary tables
OUTPUT_DIR="${PROJECT_ROOT}/results/featureCounts/summaries"
mkdir -p "$OUTPUT_DIR"

# ----------------------------- mRNA Summary ---------------------------------
output_file="${OUTPUT_DIR}/mRNA_assigned_counts.tsv"
> "$output_file"  # Clear or create file

for file in "${INPUT_DIR}"/*_mRNA_*.summary; do
    if [[ -f "$file" ]]; then
        # Extract 2nd row, 2nd column (Assigned reads)
        value=$(sed -n '2p' "$file" | awk '{print $2}')
        # Get sample ID by removing path and suffix
        sample_id=$(basename "$file" | sed 's/_mRNA_.*\.summary//')
        echo -e "${sample_id}\t${value}" >> "$output_file"
    fi
done
echo "mRNA summary saved to: $output_file"

# ----------------------------- lncRNA Summary -------------------------------
output_file="${OUTPUT_DIR}/lncRNA_assigned_counts.tsv"
> "$output_file"

for file in "${INPUT_DIR}"/*_lncRNA_*.summary; do
    if [[ -f "$file" ]]; then
        value=$(sed -n '2p' "$file" | awk '{print $2}')
        sample_id=$(basename "$file" | sed 's/_lncRNA_.*\.summary//')
        echo -e "${sample_id}\t${value}" >> "$output_file"
    fi
done
echo "lncRNA summary saved to: $output_file"

# ----------------------------- snRNA Summary --------------------------------
output_file="${OUTPUT_DIR}/snRNA_assigned_counts.tsv"
> "$output_file"

for file in "${INPUT_DIR}"/*_snRNA_*.summary; do
    if [[ -f "$file" ]]; then
        value=$(sed -n '2p' "$file" | awk '{print $2}')
        sample_id=$(basename "$file" | sed 's/_snRNA_.*\.summary//')
        echo -e "${sample_id}\t${value}" >> "$output_file"
    fi
done
echo "snRNA summary saved to: $output_file"

# ----------------------------- snoRNA Summary -------------------------------
output_file="${OUTPUT_DIR}/snoRNA_assigned_counts.tsv"
> "$output_file"

for file in "${INPUT_DIR}"/*_snoRNA_*.summary; do
    if [[ -f "$file" ]]; then
        value=$(sed -n '2p' "$file" | awk '{print $2}')
        sample_id=$(basename "$file" | sed 's/_snoRNA_.*\.summary//')
        echo -e "${sample_id}\t${value}" >> "$output_file"
    fi
done
echo "snoRNA summary saved to: $output_file"

echo "All summaries extracted. Output directory: $OUTPUT_DIR"