#!/bin/bash
# =============================================================================
# Filter VCF Files by Genotype and Depth
# =============================================================================
# This script:
#   1. Filters VCF files generated by FreeBayes (from 05_1 script)
#   2. Creates four filtered VCF sets:
#      - DP30_GT11: Depth >= 30, homozygous alternate (1/1)
#      - DP0_GT11:  Any depth, homozygous alternate (1/1)
#      - DP30_GT01: Depth >= 30, heterozygous (0/1)
#      - DP0_GT01:  Any depth, heterozygous (0/1)
#   3. Converts filtered VCF to ANNOVAR input format (.avinput)
#   4. Runs ANNOVAR annotation on each filtered set
# =============================================================================

# ----------------------------- Configuration ---------------------------------
# Project root directory (change if needed)
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

# Input/output directories (relative to PROJECT_ROOT)
VCF_IN_DIR="${PROJECT_ROOT}/results/mutation/vcf"          # Input VCF files (from 05_1)
ANNOVAR_OUT_DIR="${PROJECT_ROOT}/results/mutation/annovar" # Output directory for ANNOVAR

# ANNOVAR database and scripts (adjust paths as needed)
ANNOVAR_DB="/path/to/annovar/humandb_hg38"                 # Update to your ANNOVAR database path
ANNOVAR_SCRIPT="/path/to/annovar/table_annovar.pl"         # Update to your ANNOVAR script path
CONVERT2ANNOVAR="/path/to/annovar/convert2annovar.pl"

# Threads
THREADS=60

# Sample list file (generated by 05_1 script)
BAM_LIST="${PROJECT_ROOT}/bam_list.txt"   # or from results/mutation/annovar/bam_list.txt

# Create output directories
mkdir -p "$ANNOVAR_OUT_DIR"

# ----------------------------- Check prerequisites ---------------------------
if [ ! -f "$BAM_LIST" ]; then
    echo "ERROR: Sample list not found: $BAM_LIST"
    echo "Please run 05_1_mutation_calling.sh first to generate the list."
    exit 1
fi

if [ ! -d "$VCF_IN_DIR" ]; then
    echo "ERROR: VCF input directory not found: $VCF_IN_DIR"
    exit 1
fi

# ----------------------------- Helper function ------------------------------
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

# ----------------------------- Main processing ------------------------------
cd "$VCF_IN_DIR" || exit 1

# Read sample IDs from list
while read -r sample_id; do
    log "Processing sample: $sample_id"
    
    # Input VCF file (unfiltered, from FreeBayes)
    input_vcf="${sample_id}.vcf"
    if [ ! -f "$input_vcf" ]; then
        log "WARNING: $input_vcf not found, skipping sample $sample_id"
        continue
    fi
    
    # -------------------------------------------------------------------------
    # 1. Filter homozygous alternate (GT=1/1) with DP>=30
    # -------------------------------------------------------------------------
    output_vcf1="${sample_id}_filtered_DP30_GT11.vcf"
    bcftools view -i 'FORMAT/DP>=30 && FORMAT/GT="1/1"' "$input_vcf" -o "$output_vcf1"
    
    # -------------------------------------------------------------------------
    # 2. Filter homozygous alternate (GT=1/1) without depth filter
    # -------------------------------------------------------------------------
    output_vcf2="${sample_id}_filtered_DP0_GT11.vcf"
    bcftools view -i 'FORMAT/GT="1/1"' "$input_vcf" -o "$output_vcf2"
    
    # -------------------------------------------------------------------------
    # 3. Filter heterozygous (GT=0/1) with DP>=30
    # -------------------------------------------------------------------------
    output_vcf3="${sample_id}_filtered_DP30_GT01.vcf"
    bcftools view -i 'FORMAT/DP>=30 && FORMAT/GT="0/1"' "$input_vcf" -o "$output_vcf3"
    
    # -------------------------------------------------------------------------
    # 4. Filter heterozygous (GT=0/1) without depth filter
    # -------------------------------------------------------------------------
    output_vcf4="${sample_id}_filtered_DP0_GT01.vcf"
    bcftools view -i 'FORMAT/GT="0/1"' "$input_vcf" -o "$output_vcf4"
    
    # -------------------------------------------------------------------------
    # 5. Convert filtered VCFs to ANNOVAR .avinput format
    # -------------------------------------------------------------------------
    for suffix in DP30_GT11 DP0_GT11 DP30_GT01 DP0_GT01; do
        vcf_file="${sample_id}_filtered_${suffix}.vcf"
        avinput_file="${ANNOVAR_OUT_DIR}/${sample_id}_filtered_${suffix}.avinput"
        if [ -f "$vcf_file" ] && [ -s "$vcf_file" ]; then
            perl "$CONVERT2ANNOVAR" -format vcf4old "$vcf_file" -outfile "$avinput_file"
            log "Converted $vcf_file to avinput"
        else
            log "WARNING: $vcf_file empty or missing, skipping ANNOVAR conversion"
        fi
    done
    
    # -------------------------------------------------------------------------
    # 6. Run ANNOVAR annotation on each avinput file (in parallel later)
    # -------------------------------------------------------------------------
    # Note: We'll run ANNOVAR in a separate parallel loop for efficiency
    
done < "$BAM_LIST"

# -----------------------------------------------------------------------------
# 7. Parallel ANNOVAR annotation for all samples and all filter types
# -----------------------------------------------------------------------------
cd "$ANNOVAR_OUT_DIR" || exit 1

# Generate list of all avinput files
find . -name "*_filtered_*.avinput" -type f | sed 's/\.\/\(.*\)\.avinput/\1/' > avinput_list.txt

cat avinput_list.txt | parallel -j "$THREADS" '
    base={}
    log "ANNOVAR annotation for $base"
    perl "'"$ANNOVAR_SCRIPT"'" ${base}.avinput "'"$ANNOVAR_DB"'" \
        -buildver hg38 -out "$base" \
        -protocol refGeneWithVer,cytoBand,gnomad211_exome,avsnp151,dbnsfp47a \
        -operation gx,r,f,f,f -xref /path/to/gene_xref.txt -remove -nastring . -csvout -polish
'

rm -f avinput_list.txt

log "All filtering and annotation completed."
log "Outputs saved to: $ANNOVAR_OUT_DIR"