#!/bin/bash
# =============================================================================
# Extract Depth Information from VCF Files
# =============================================================================
# This script:
#   1. Reads sample list (bam_list.txt)
#   2. For each sample, extracts depth (DP) information from VCF
#   3. Outputs a tab-separated file: CHROM, POS, DP
#   4. Saves depth info to the ANNOVAR output directory
# =============================================================================

# ----------------------------- Configuration ---------------------------------
# Project root directory (change if needed)
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

# Input/output directories (relative to PROJECT_ROOT)
VCF_IN_DIR="${PROJECT_ROOT}/results/mutation/vcf"          # Input VCF files (from 05_1)
DEPTH_OUT_DIR="${PROJECT_ROOT}/results/mutation/annovar"   # Output directory for depth files

# Sample list file (generated by 05_1 script)
BAM_LIST="${PROJECT_ROOT}/bam_list.txt"

# Create output directory
mkdir -p "$DEPTH_OUT_DIR"

# ----------------------------- Helper function ------------------------------
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

# ----------------------------- Check prerequisites ---------------------------
if [ ! -f "$BAM_LIST" ]; then
    echo "ERROR: Sample list not found: $BAM_LIST"
    echo "Please run 05_1_mutation_calling.sh first to generate the list."
    exit 1
fi

if [ ! -d "$VCF_IN_DIR" ]; then
    echo "ERROR: VCF input directory not found: $VCF_IN_DIR"
    exit 1
fi

# ----------------------------- Extract depth info ---------------------------
cd "$VCF_IN_DIR" || exit 1

while read -r sample_id; do
    log "Processing sample: $sample_id"
    
    input_vcf="${sample_id}.vcf"
    output_dp="${DEPTH_OUT_DIR}/${sample_id}_dp_info.txt"
    
    if [ ! -f "$input_vcf" ]; then
        log "WARNING: $input_vcf not found, skipping sample $sample_id"
        continue
    fi
    
    # Extract CHROM, POS, DP from VCF
    # Format: %CHROM\t%POS\t%DP\n
    bcftools query -f '%CHROM\t%POS\t%DP\n' "$input_vcf" > "$output_dp"
    
    # Count lines extracted
    line_count=$(wc -l < "$output_dp")
    log "Extracted $line_count depth records for $sample_id"
    
done < "$BAM_LIST"

log "Depth extraction completed."
log "Output files saved to: $DEPTH_OUT_DIR"